#ifndef _HOME_HVS_DOCUMENTS_PLATFORMIO_PROJECTS_LORA_RADIO_LIB_LORARADIO_MODULEENUMBASE_MODULEENUMBASE_HPP
#define _HOME_HVS_DOCUMENTS_PLATFORMIO_PROJECTS_LORA_RADIO_LIB_LORARADIO_MODULEENUMBASE_MODULEENUMBASE_HPP


using uint8_t = unsigned char;
enum class ModuleStatus: uint8_t {
    OK,
    FAIL,
    EMPTY_RETURN_BUFFER,
    EMPTY_BUFFER_WRITTEN,
    NOT_WRITABLE,
    JOB_TIMEOUT,
    NOT_IMPLEMENTED,
    
};
#endif
